context:
  version: 0.7.1

package:
  name: amp
  version: ${{ version }}

source:
  url: https://github.com/jmacdonald/amp/archive/${{ version }}.tar.gz
  sha256: 59a65c2c4592eed188433fe7c4bf2ba84206f217bdafc5a2c7f97623f5607c12

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - python
  host:
    - ${{ libxcb if linux }}
    - zlib

tests:
  - script:
      - "amp 2>&1 | grep -q \"\""

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Text editor for your terminal
  homepage: https://github.com/jmacdonald/amp
  repository: https://github.com/jmacdonald/amp

extra:
  recipe-maintainers:
    - danielnachun
